error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (D:\FunDoNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:26:35
    at Generator.next (<anonymous>)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\FunDoNotes\src\middlewares\auth.middleware.ts:4:12)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:13:82
    at Layer.handle [as handle_request] (D:\FunDoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\FunDoNotes\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\FunDoNotes\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\FunDoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\FunDoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\FunDoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\FunDoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\FunDoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\FunDoNotes\node_modules\express\lib\router\index.js:47:12) 
    url - /api/v1/notes/ 
    method - GET 
    IP - ::1
   {"timestamp":"2024-12-03T05:38:21.391Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (D:\FunDoNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:26:35
    at Generator.next (<anonymous>)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\FunDoNotes\src\middlewares\auth.middleware.ts:4:12)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:13:82
    at Layer.handle [as handle_request] (D:\FunDoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\FunDoNotes\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\FunDoNotes\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\FunDoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\FunDoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\FunDoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\FunDoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\FunDoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\FunDoNotes\node_modules\express\lib\router\index.js:47:12) 
    url - /api/v1/notes 
    method - GET 
    IP - ::1
   {"timestamp":"2024-12-03T05:38:34.088Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (D:\FunDoNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:26:35
    at Generator.next (<anonymous>)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\FunDoNotes\src\middlewares\auth.middleware.ts:4:12)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:13:82
    at Layer.handle [as handle_request] (D:\FunDoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\FunDoNotes\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\FunDoNotes\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\FunDoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\FunDoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\FunDoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\FunDoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\FunDoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\FunDoNotes\node_modules\express\lib\router\index.js:47:12) 
    url - /api/v1/notes/ 
    method - GET 
    IP - ::1
   {"timestamp":"2024-12-03T05:38:36.259Z"}
error: 
    status - 500 
    message - JsonWebTokenError: jwt malformed
    at Object.module.exports [as verify] (D:\FunDoNotes\node_modules\jsonwebtoken\verify.js:63:17)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:26:35
    at Generator.next (<anonymous>)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\FunDoNotes\src\middlewares\auth.middleware.ts:4:12)
    at D:\FunDoNotes\src\middlewares\auth.middleware.ts:13:82
    at Layer.handle [as handle_request] (D:\FunDoNotes\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\FunDoNotes\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (D:\FunDoNotes\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (D:\FunDoNotes\node_modules\express\lib\router\layer.js:95:5)
    at D:\FunDoNotes\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (D:\FunDoNotes\node_modules\express\lib\router\index.js:346:12)
    at next (D:\FunDoNotes\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (D:\FunDoNotes\node_modules\express\lib\router\index.js:175:3)
    at router (D:\FunDoNotes\node_modules\express\lib\router\index.js:47:12) 
    url - /api/v1/notes/ 
    method - GET 
    IP - ::1
   {"timestamp":"2024-12-03T05:38:38.024Z"}
